basepath=/builds/simpl/simpl-open/development/iaa/fe-users-and-roles
coverageBasepath=${basepath}/coverage

sonar.sources=${basepath}/src

sonar.javascript.lcov.reportPaths=${coverageBasepath}/lcov.info
sonar.exclusions=src/app/shared/api-clients/**,**/*.spec.ts,src/index.html
sonar.coverage.exclusions=src/bootstrap.ts,src/main.ts,src/environments/**,src/config/**,src/*.routes.ts,src/**/mocks/**,src/**/*.mock.ts,**/*.config.ts,**/remote-entry/**,**/assets/**,**/test-setup.ts,src/app/shared/api-clients/**

